services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: dms-api
    ports:      # chỉ cần nội bộ network
      - "8000:8000"
    # volumes:     # nếu muốn cập nhật model mà không rebuild
    #   - ./Models:/app/Models
    environment:
      YOLO_CONFIG_DIR: /tmp/ultralytics_config

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    container_name: dms-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./Videos:/app/videos
